FlightBooking5/FlightBooking5/Models/ImageAd.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
namespace FlightBooking5.Models
{
    public class ImageAd
    {
        [Key]
        public int ImageId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        [NotMapped]
        public IFormFile Photo { get; set; } // Thuộc tính để nhận file ảnh từ form
        public string PhotoPath { get; set; } // Đường dẫn của ảnh trong thư mục "wwwroot/img"
        public string PhotoName { get; set; } // Tên file ảnh
    }
}

FlightBooking5/FlightBooking5/Controllers/ImageAdsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FlightBooking5.Data;
using FlightBooking5.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;

namespace FlightBooking5.Controllers
{
    public class ImageAdsController : Controller
    {
        private readonly FlightBooking5Context _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ImageAdsController(FlightBooking5Context context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: ImageAds
        [Authorize(Roles = "Admin Manager,Marketing")]
        public async Task<IActionResult> Index()
        {
                  return _context.ImageAd != null ? 
                              View(await _context.ImageAd.ToListAsync()) :
                              Problem("Entity set 'FlightBooking5Context.ImageAd'  is null.");
        }
        [Authorize(Roles = "Admin Manager,Marketing")]
        // GET: ImageAds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ImageAd == null)
            {
                return NotFound();
            }

            var imageAd = await _context.ImageAd
                .FirstOrDefaultAsync(m => m.ImageId == id);
            if (imageAd == null)
            {
                return NotFound();
            }

            return View(imageAd);
        }
        [Authorize(Roles = "Admin Manager,Marketing")]
        // GET: ImageAds/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ImageAds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ImageAd imageAd)
        {
            if (imageAd.Photo != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "img");

                // Tạo tên file duy nhất bằng cách kết hợp tên file gốc với một số ngẫu nhiên
                string uniqueFileName = Guid.NewGuid().ToString() + "_" + imageAd.Photo.FileName;

                // Kết hợp đường dẫn thư mục và tên file để có đường dẫn lưu file
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                // Lưu file vào đường dẫn được chỉ định
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    imageAd.Photo.CopyTo(fileStream);
                }
                imageAd.PhotoPath = "/img/" + uniqueFileName;
                imageAd.PhotoName = uniqueFileName;
                var entity = new ImageAd
                {
                    Title = imageAd.Title,
                    Content = imageAd.Content,
                    PhotoPath = imageAd.PhotoPath,
                    PhotoName = imageAd.PhotoName
                };
                _context.Add(entity);
                await _context.SaveChangesAsync();
                
                return RedirectToAction("Ads", "Admin");
            }
            return View(imageAd);
        }
        [Authorize(Roles = "Admin Manager,Marketing")]
        // GET: ImageAds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ImageAd == null)
            {
                return NotFound();
            }

            var imageAd = await _context.ImageAd.FindAsync(id);
            if (imageAd == null)
            {
                return NotFound();
            }
            return View(imageAd);
        }

        // POST: ImageAds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ImageId,Title,Content,PhotoPath,PhotoName")] ImageAd imageAd)
        {
            if (id != imageAd.ImageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(imageAd);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImageAdExists(imageAd.ImageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Ads", "Admin");
            }
            return View(imageAd);
        }
        [Authorize(Roles = "Admin Manager,Marketing")]
        // GET: ImageAds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ImageAd == null)
            {
                return NotFound();
            }

            var imageAd = await _context.ImageAd
                .FirstOrDefaultAsync(m => m.ImageId == id);
            if (imageAd == null)
            {
                return NotFound();
            }

            return View(imageAd);
        }

        // POST: ImageAds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ImageAd == null)
            {
                return Problem("Entity set 'FlightBooking5Context.ImageAd'  is null.");
            }
            var imageAd = await _context.ImageAd.FindAsync(id);
            if (imageAd != null)
            {
                _context.ImageAd.Remove(imageAd);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("Ads", "Admin");
        }

        private bool ImageAdExists(int id)
        {
          return (_context.ImageAd?.Any(e => e.ImageId == id)).GetValueOrDefault();
        }
    }
}

FlightBooking5/FlightBooking5/Views/ImageAds/Create.cshtml
@model FlightBooking5.Models.ImageAd




<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
	<meta name="author" content="AdminKit">
	<meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="shortcut icon" href="/img/icons/icon-48x48.png" />

	<link rel="canonical" href="https://demo-basic.adminkit.io/" />

	<title>AdminKit Demo - Bootstrap 5 Admin Template</title>

	<link href="/css/app.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
</head>

<body>
	<div class="wrapper">
		<nav id="sidebar" class="sidebar js-sidebar">
			<div class="sidebar-content js-simplebar">
				<a class="sidebar-brand" href="index.html">
					<span class="align-middle">AdminKit</span>
				</a>

				<ul class="sidebar-nav">
				<li class="sidebar-header">
					Admin Manager
				</li>



				<li class="sidebar-item">
					<a class="sidebar-link" href="/Admin/AddFlight">
						<i class="align-middle" data-feather="book"></i> <span class="align-middle">Add Flight</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a class="sidebar-link" href="/Admin/AddRole">
						<i class="align-middle" data-feather="book"></i> <span class="align-middle">Add Role</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a class="sidebar-link" href="/Admin/PaymentDetails">
						<i class="align-middle" data-feather="book"></i> <span class="align-middle">Payment Details</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a class="sidebar-link" href="/Admin/EmployeeAssignment">
						<i class="align-middle" data-feather="book"></i> <span class="align-middle">Employee Assignment</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a class="sidebar-link" href="/Admin/InputUser">
						<i class="align-middle" data-feather="book"></i> <span class="align-middle">Change Role</span>
					</a>
				</li>


				<li class="sidebar-header">
					Employee
				</li>
				<li class="sidebar-item">
					<a class="sidebar-link" href="/Admin/EmployeeSchedule">
							<i class="align-middle" data-feather="book"></i> <span class="align-middle">Employee Schedule</span>
					</a>
				</li>
				<li class="sidebar-header">
					Marketing
				</li>
				<li class="sidebar-item">
					<a class="sidebar-link" href="/Admin/Ads">
						<i class="align-middle" data-feather="book"></i> <span class="align-middle">Advertisement</span>
					</a>
				</li>
				</ul>

			</div>
		</nav>

				<div class="main">
					<nav class="navbar navbar-expand navbar-light navbar-bg">
						<a class="sidebar-toggle js-sidebar-toggle">
							<i class="hamburger align-self-center"></i>
						</a>
					</nav>

					<main class="content">
						<div class="container-fluid">

							<h1 class="h3 mb-3">Create</h1>

							<div class="row">
								<div class="col-12">
									<div class="card">
										<div class="card-header">
											<h5 class="card-title mb-0"><a asp-controller="Admin"asp-action="Ads"> Back</a></h5>
										</div>
										<div class="card-body">

											@if (ViewBag.Message != null)
											{
												<div class="alert alert-success">@ViewBag.Message</div>
											}
											<div class="row">
												<div class="col-md-4">
													<form asp-controller="ImageAds"asp-action="Create" method="post" enctype="multipart/form-data">
														<div asp-validation-summary="ModelOnly" class="text-danger"></div>
														<div class="form-group">
															<label asp-for="Title" class="control-label"></label>
															<input asp-for="Title" class="form-control" />
															<span asp-validation-for="Title" class="text-danger"></span>
														</div>
														<div class="form-group">
															<label asp-for="Content" class="control-label"></label>
															<input asp-for="Content" class="form-control" />
															<span asp-validation-for="Content" class="text-danger"></span>
														</div>
														<div class="form-group">
															<label asp-for="Photo"></label>
															<input asp-for="Photo" type="file" class="form-control-file" />
														</div>

														<div class="form-group">
															<input type="submit" value="Upload" class="btn btn-primary" />
														</div>
													</form>
												</div>
											</div>
					</main>


				</div>
			</div>

			<script src="/js/app.js"></script>

			<script>
				document.addEventListener("DOMContentLoaded", function () {
					var ctx = document.getElementById("chartjs-dashboard-line").getContext("2d");
					var gradient = ctx.createLinearGradient(0, 0, 0, 225);
					gradient.addColorStop(0, "rgba(215, 227, 244, 1)");
					gradient.addColorStop(1, "rgba(215, 227, 244, 0)");
					// Line chart
					new Chart(document.getElementById("chartjs-dashboard-line"), {
						type: "line",
						data: {
							labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
							datasets: [{
								label: "Sales ($)",
								fill: true,
								backgroundColor: gradient,
								borderColor: window.theme.primary,
								data: [
									2115,
									1562,
									1584,
									1892,
									1587,
									1923,
									2566,
									2448,
									2805,
									3438,
									2917,
									3327
								]
							}]
						},
						options: {
							maintainAspectRatio: false,
							legend: {
								display: false
							},
							tooltips: {
								intersect: false
							},
							hover: {
								intersect: true
							},
							plugins: {
								filler: {
									propagate: false
								}
							},
							scales: {
								xAxes: [{
									reverse: true,
									gridLines: {
										color: "rgba(0,0,0,0.0)"
									}
								}],
								yAxes: [{
									ticks: {
										stepSize: 1000
									},
									display: true,
									borderDash: [3, 3],
									gridLines: {
										color: "rgba(0,0,0,0.0)"
									}
								}]
							}
						}
					});
				});
			</script>
			<script>
				document.addEventListener("DOMContentLoaded", function () {
					// Pie chart
					new Chart(document.getElementById("chartjs-dashboard-pie"), {
						type: "pie",
						data: {
							labels: ["Chrome", "Firefox", "IE"],
							datasets: [{
								data: [4306, 3801, 1689],
								backgroundColor: [
									window.theme.primary,
									window.theme.warning,
									window.theme.danger
								],
								borderWidth: 5
							}]
						},
						options: {
							responsive: !window.MSInputMethodContext,
							maintainAspectRatio: false,
							legend: {
								display: false
							},
							cutoutPercentage: 75
						}
					});
				});
			</script>
			<script>
				document.addEventListener("DOMContentLoaded", function () {
					// Bar chart
					new Chart(document.getElementById("chartjs-dashboard-bar"), {
						type: "bar",
						data: {
							labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
							datasets: [{
								label: "This year",
								backgroundColor: window.theme.primary,
								borderColor: window.theme.primary,
								hoverBackgroundColor: window.theme.primary,
								hoverBorderColor: window.theme.primary,
								data: [54, 67, 41, 55, 62, 45, 55, 73, 60, 76, 48, 79],
								barPercentage: .75,
								categoryPercentage: .5
							}]
						},
						options: {
							maintainAspectRatio: false,
							legend: {
								display: false
							},
							scales: {
								yAxes: [{
									gridLines: {
										display: false
									},
									stacked: false,
									ticks: {
										stepSize: 20
									}
								}],
								xAxes: [{
									stacked: false,
									gridLines: {
										color: "transparent"
									}
								}]
							}
						}
					});
				});
			</script>
			<script>
				document.addEventListener("DOMContentLoaded", function () {
					var markers = [{
						coords: [31.230391, 121.473701],
						name: "Shanghai"
					},
					{
						coords: [28.704060, 77.102493],
						name: "Delhi"
					},
					{
						coords: [6.524379, 3.379206],
						name: "Lagos"
					},
					{
						coords: [35.689487, 139.691711],
						name: "Tokyo"
					},
					{
						coords: [23.129110, 113.264381],
						name: "Guangzhou"
					},
					{
						coords: [40.7127837, -74.0059413],
						name: "New York"
					},
					{
						coords: [34.052235, -118.243683],
						name: "Los Angeles"
					},
					{
						coords: [41.878113, -87.629799],
						name: "Chicago"
					},
					{
						coords: [51.507351, -0.127758],
						name: "London"
					},
					{
						coords: [40.416775, -3.703790],
						name: "Madrid "
					}
					];
					var map = new jsVectorMap({
						map: "world",
						selector: "#world_map",
						zoomButtons: true,
						markers: markers,
						markerStyle: {
							initial: {
								r: 9,
								strokeWidth: 7,
								stokeOpacity: .4,
								fill: window.theme.primary
							},
							hover: {
								fill: window.theme.primary,
								stroke: window.theme.primary
							}
						},
						zoomOnScroll: false
					});
					window.addEventListener("resize", () => {
						map.updateSize();
					});
				});
			</script>
			<script>
				document.addEventListener("DOMContentLoaded", function () {
					var date = new Date(Date.now() - 5 * 24 * 60 * 60 * 1000);
					var defaultDate = date.getUTCFullYear() + "-" + (date.getUTCMonth() + 1) + "-" + date.getUTCDate();
					document.getElementById("datetimepicker-dashboard").flatpickr({
						inline: true,
						prevArrow: "<span title=\"Previous month\">&laquo;</span>",
						nextArrow: "<span title=\"Next month\">&raquo;</span>",
						defaultDate: defaultDate
					});
				});
			</script>

</body>

</html>

FlightBooking5/FlightBooking5/Views/ImageAds/Delete.cshtml
@model FlightBooking5.Models.ImageAd






<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
	<meta name="author" content="AdminKit">
	<meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="shortcut icon" href="/img/icons/icon-48x48.png" />

	<link rel="canonical" href="https://demo-basic.adminkit.io/" />

	<title>AdminKit Demo - Bootstrap 5 Admin Template</title>

	<link href="/css/app.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
</head>

<body>
	<div class="wrapper">
		<nav id="sidebar" class="sidebar js-sidebar">
			<div class="sidebar-content js-simplebar">
				<a class="sidebar-brand" href="index.html">
					<span class="align-middle">AdminKit</span>
				</a>

				<ul class="sidebar-nav">
				<li class="sidebar-header">
					Admin Manager
				</li>



				<li class="sidebar-item">
					<a class="sidebar-link" href="/Admin/AddFlight">
						<i class="align-middle" data-feather="book"></i> <span class="align-middle">Add Flight</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a class="sidebar-link" href="/Admin/AddRole">
						<i class="align-middle" data-feather="book"></i> <span class="align-middle">Add Role</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a class="sidebar-link" href="/Admin/PaymentDetails">
						<i class="align-middle" data-feather="book"></i> <span class="align-middle">Payment Details</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a class="sidebar-link" href="/Admin/EmployeeAssignment">
						<i class="align-middle" data-feather="book"></i> <span class="align-middle">Employee Assignment</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a class="sidebar-link" href="/Admin/InputUser">
						<i class="align-middle" data-feather="book"></i> <span class="align-middle">Change Role</span>
					</a>
				</li>


				<li class="sidebar-header">
					Employee
				</li>
				<li class="sidebar-item">
					<a class="sidebar-link" href="/Admin/EmployeeSchedule">
							<i class="align-middle" data-feather="book"></i> <span class="align-middle">Employee Schedule</span>
					</a>
				</li>
				<li class="sidebar-header">
					Marketing
				</li>
				<li class="sidebar-item">
					<a class="sidebar-link" href="/Admin/Ads">
						<i class="align-middle" data-feather="book"></i> <span class="align-middle">Advertisement</span>
					</a>
				</li>
				</ul>
			</div>
		</nav>

				<div class="main">
					<nav class="navbar navbar-expand navbar-light navbar-bg">
						<a class="sidebar-toggle js-sidebar-toggle">
							<i class="hamburger align-self-center"></i>
						</a>
					</nav>

					<main class="content">
						<div class="container-fluid">

							<h1 class="h3 mb-3">Delete</h1>

							<div class="row">
								<div class="col-12">
									<div class="card">
										<div class="card-header">
											<h5 class="card-title mb-0"><a asp-controller="Admin"asp-action="Ads"> Back</a></h5>
										</div>
										<div class="card-body">
											<div>
												
												<dl class="row">
													<dt class="col-sm-2">
														@Html.DisplayNameFor(model => model.Title)
													</dt>
													<dd class="col-sm-10">
														@Html.DisplayFor(model => model.Title)
													</dd>
													<dt class="col-sm-2">
														@Html.DisplayNameFor(model => model.Content)
													</dt>
													<dd class="col-sm-10">
														@Html.DisplayFor(model => model.Content)
													</dd>
													<dt class="col-sm-2">
														@Html.DisplayNameFor(model => model.PhotoPath)
													</dt>
													<dd class="col-sm-10">
														@Html.DisplayFor(model => model.PhotoPath)
													</dd>
													<dt class="col-sm-2">
														@Html.DisplayNameFor(model => model.PhotoName)
													</dt>
													<dd class="col-sm-10">
														@Html.DisplayFor(model => model.PhotoName)
													</dd>
												</dl>

												<form asp-action="Delete">
													<input type="hidden" asp-controller="ImageAds" asp-for="ImageId" />
													<input type="submit" value="Delete" class="btn btn-danger" /> |
													
												</form>
											</div>
					</main>


				</div>
			</div>

			<script src="/js/app.js"></script>

			<script>
				document.addEventListener("DOMContentLoaded", function () {
					var ctx = document.getElementById("chartjs-dashboard-line").getContext("2d");
					var gradient = ctx.createLinearGradient(0, 0, 0, 225);
					gradient.addColorStop(0, "rgba(215, 227, 244, 1)");
					gradient.addColorStop(1, "rgba(215, 227, 244, 0)");
					// Line chart
					new Chart(document.getElementById("chartjs-dashboard-line"), {
						type: "line",
						data: {
							labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
							datasets: [{
								label: "Sales ($)",
								fill: true,
								backgroundColor: gradient,
								borderColor: window.theme.primary,
								data: [
									2115,
									1562,
									1584,
									1892,
									1587,
									1923,
									2566,
									2448,
									2805,
									3438,
									2917,
									3327
								]
							}]
						},
						options: {
							maintainAspectRatio: false,
							legend: {
								display: false
							},
							tooltips: {
								intersect: false
							},
							hover: {
								intersect: true
							},
							plugins: {
								filler: {
									propagate: false
								}
							},
							scales: {
								xAxes: [{
									reverse: true,
									gridLines: {
										color: "rgba(0,0,0,0.0)"
									}
								}],
								yAxes: [{
									ticks: {
										stepSize: 1000
									},
									display: true,
									borderDash: [3, 3],
									gridLines: {
										color: "rgba(0,0,0,0.0)"
									}
								}]
							}
						}
					});
				});
			</script>
			<script>
				document.addEventListener("DOMContentLoaded", function () {
					// Pie chart
					new Chart(document.getElementById("chartjs-dashboard-pie"), {
						type: "pie",
						data: {
							labels: ["Chrome", "Firefox", "IE"],
							datasets: [{
								data: [4306, 3801, 1689],
								backgroundColor: [
									window.theme.primary,
									window.theme.warning,
									window.theme.danger
								],
								borderWidth: 5
							}]
						},
						options: {
							responsive: !window.MSInputMethodContext,
							maintainAspectRatio: false,
							legend: {
								display: false
							},
							cutoutPercentage: 75
						}
					});
				});
			</script>
			<script>
				document.addEventListener("DOMContentLoaded", function () {
					// Bar chart
					new Chart(document.getElementById("chartjs-dashboard-bar"), {
						type: "bar",
						data: {
							labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
							datasets: [{
								label: "This year",
								backgroundColor: window.theme.primary,
								borderColor: window.theme.primary,
								hoverBackgroundColor: window.theme.primary,
								hoverBorderColor: window.theme.primary,
								data: [54, 67, 41, 55, 62, 45, 55, 73, 60, 76, 48, 79],
								barPercentage: .75,
								categoryPercentage: .5
							}]
						},
						options: {
							maintainAspectRatio: false,
							legend: {
								display: false
							},
							scales: {
								yAxes: [{
									gridLines: {
										display: false
									},
									stacked: false,
									ticks: {
										stepSize: 20
									}
								}],
								xAxes: [{
									stacked: false,
									gridLines: {
										color: "transparent"
									}
								}]
							}
						}
					});
				});
			</script>
			<script>
				document.addEventListener("DOMContentLoaded", function () {
					var markers = [{
						coords: [31.230391, 121.473701],
						name: "Shanghai"
					},
					{
						coords: [28.704060, 77.102493],
						name: "Delhi"
					},
					{
						coords: [6.524379, 3.379206],
						name: "Lagos"
					},
					{
						coords: [35.689487, 139.691711],
						name: "Tokyo"
					},
					{
						coords: [23.129110, 113.264381],
						name: "Guangzhou"
					},
					{
						coords: [40.7127837, -74.0059413],
						name: "New York"
					},
					{
						coords: [34.052235, -118.243683],
						name: "Los Angeles"
					},
					{
						coords: [41.878113, -87.629799],
						name: "Chicago"
					},
					{
						coords: [51.507351, -0.127758],
						name: "London"
					},
					{
						coords: [40.416775, -3.703790],
						name: "Madrid "
					}
					];
					var map = new jsVectorMap({
						map: "world",
						selector: "#world_map",
						zoomButtons: true,
						markers: markers,
						markerStyle: {
							initial: {
								r: 9,
								strokeWidth: 7,
								stokeOpacity: .4,
								fill: window.theme.primary
							},
							hover: {
								fill: window.theme.primary,
								stroke: window.theme.primary
							}
						},
						zoomOnScroll: false
					});
					window.addEventListener("resize", () => {
						map.updateSize();
					});
				});
			</script>
			<script>
				document.addEventListener("DOMContentLoaded", function () {
					var date = new Date(Date.now() - 5 * 24 * 60 * 60 * 1000);
					var defaultDate = date.getUTCFullYear() + "-" + (date.getUTCMonth() + 1) + "-" + date.getUTCDate();
					document.getElementById("datetimepicker-dashboard").flatpickr({
						inline: true,
						prevArrow: "<span title=\"Previous month\">&laquo;</span>",
						nextArrow: "<span title=\"Next month\">&raquo;</span>",
						defaultDate: defaultDate
					});
				});
			</script>

</body>

</html>

FlightBooking5/FlightBooking5/Views/ImageAds/Index.cshtml
@model IEnumerable<FlightBooking5.Models.ImageAd>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhotoPath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhotoName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhotoPath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhotoName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ImageId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ImageId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ImageId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>